name: Nodejs CI

on: [push]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm run format
      - run: npm run format:check
      - run: npm run test

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm run build
    